# TODOs:
# - check if contracts are deployed correctly
# - register operators
# - set up S3 bucket
# - verify AWS params
# - check if we need to provide unique private keys to each service
# - # https://github.com/Layr-Labs/eigenda/blob/4ec69dc0cb88182bb6e6fb8054e8db4d6086200d/inabox/deploy/localstack.go#L47-L50
deployments:
  - name: EigenDA
    repo: https://github.com/Layr-Labs/eigenda.git
    ref: master
    contracts_path: contracts
    script: script/SetUpEigenDA.s.sol:SetupEigenDA
    input:
      script/input/: eigenda_deploy_config
    output:
      eigenda_addresses: script/output/eigenda_deploy_output.json
    addresses:
      serviceManager: "eigenda_addresses:.eigenDAServiceManager"
      operatorStateRetriever: "eigenda_addresses:.operatorStateRetriever"

  - name: MockRollup
    repo: https://github.com/Layr-Labs/eigenda.git
    ref: master
    contracts_path: contracts
    script: script/MockRollupDeployer.s.sol:MockRollupDeployer
    extra_args: "--sig 'run(address)' -- $EIGENDA_SERVICE_MANAGER"
    env:
      EIGENDA_SERVICE_MANAGER: "{{.addresses.EigenDA.serviceManager}}"

services:
  - name: node
    image: eigenda-node
    build_cmd: "docker build . -t eigenda-node --target node"
    ports:
      dispersal:
        number: 8080
        transport_protocol: TCP
        application_protocol: "grpc"
      retrieval:
        number: 8081
        transport_protocol: TCP
        application_protocol: "grpc"
      nodeapi:
        number: 9091
        transport_protocol: TCP
        application_protocol: "http"
      metrics:
        number: 9100
        transport_protocol: TCP
        application_protocol: "http"
    input:
      /kzg/: kzg_config
      /keys/ecdsa: operator1_ecdsa
      /keys/bls: operator1_bls
    env:
      NODE_LOG_LEVEL: debug
      NODE_VERBOSE: true
      NODE_HOSTNAME: node
      NODE_DISPERSAL_PORT: 8080
      NODE_RETRIEVAL_PORT: 8081
      NODE_ENABLE_METRICS: true
      NODE_METRICS_PORT: 9100
      NODE_ENABLE_NODE_API: true
      NODE_API_PORT: 9091
      NODE_TIMEOUT: "20s"
      NODE_QUORUM_ID_LIST: "0,1"
      NODE_DB_PATH: "/var/nodedb"
      NODE_BLS_OPERATOR_STATE_RETRIVER: "{{.addresses.EigenDA.operatorStateRetriever}}"
      NODE_EIGENDA_SERVICE_MANAGER: "{{.addresses.EigenDA.serviceManager}}"
      # TODO: find a way to provide correct IP address, or if it's even needed
      NODE_PUBLIC_IP_PROVIDER: mockip
      NODE_CHURNER_URL: "{{.services.churner.ip_address}}"
      NODE_G1_PATH: /kzg/g1.point
      NODE_G2_PATH: /kzg/g2.point
      NODE_CACHE_PATH: /kzg/cache
      NODE_SRS_ORDER: 3000
      NODE_SRS_LOAD: 2900
      NODE_CHAIN_RPC: "{{.http_rpc_url}}"
      # TODO: check if we need this, and provide provide a unique one
      NODE_PRIVATE_KEY: "{{slice .keys.operator1_ecdsa.private_key 2}}"
      NODE_ECDSA_KEY_FILE: /keys/ecdsa/keys/1.ecdsa.key.json
      NODE_ECDSA_KEY_PASSWORD: "{{.keys.operator1_ecdsa.password}}"
      NODE_BLS_KEY_FILE: /keys/bls/keys/1.bls.key.json
      NODE_BLS_KEY_PASSWORD: "{{.keys.operator1_bls.password}}"
      NODE_REGISTER_AT_NODE_START: true
      NODE_PUBLIC_IP_CHECK_INTERVAL: 0

  - name: localstack
    image: localstack/localstack
    env:
      DEBUG: 1
    ports:
      gateway:
        number: 4566
        transport_protocol: TCP
        application_protocol: "http"
    cmd: []

  - name: create-s3-bucket
    image: amazon/aws-cli:2.13.2
    env:
      AWS_ACCESS_KEY_ID: "localstack"
      AWS_SECRET_ACCESS_KEY: "localstack"
    cmd:
      - "s3api"
      - "create-bucket"
      - "--endpoint-url=http://{{.services.localstack.ip_address}}:4566/"
      - "--bucket"
      - "test-eigenda-blobstore"
      - "--region"
      - "us-east-1"

  - name: create-dynamo-metadata-table
    image: amazon/aws-cli:2.13.2
    env:
      AWS_ACCESS_KEY_ID: "localstack"
      AWS_SECRET_ACCESS_KEY: "localstack"
    cmd:
      - "dynamodb"
      - "create-table"
      - "--table-name"
      - "test-BlobMetadata"
      - "--attribute-definitions"
      - "AttributeName=BlobHash,AttributeType=S"
      - "AttributeName=MetadataHash,AttributeType=S"
      - "AttributeName=BlobStatus,AttributeType=N"
      - "AttributeName=RequestedAt,AttributeType=N"
      - "AttributeName=BatchHeaderHash,AttributeType=B"
      - "AttributeName=BlobIndex,AttributeType=N"
      - "AttributeName=Expiry,AttributeType=N"
      - "--key-schema"
      - "AttributeName=BlobHash,KeyType=HASH"
      - "AttributeName=MetadataHash,KeyType=RANGE"
      - "--provisioned-throughput"
      - "ReadCapacityUnits=10,WriteCapacityUnits=10"
      - "--global-secondary-indexes"
      - '[{"IndexName": "StatusIndex", "KeySchema": [{"AttributeName": "BlobStatus", "KeyType": "HASH"},{"AttributeName": "RequestedAt", "KeyType": "RANGE"}],"Projection": {"ProjectionType": "ALL"},"ProvisionedThroughput": {"ReadCapacityUnits": 5, "WriteCapacityUnits": 5}},{"IndexName": "BatchIndex","KeySchema": [{"AttributeName": "BatchHeaderHash", "KeyType": "HASH"},{"AttributeName": "BlobIndex", "KeyType": "RANGE"}],"Projection": {"ProjectionType": "ALL"},"ProvisionedThroughput": {"ReadCapacityUnits": 5, "WriteCapacityUnits": 5}},{"IndexName": "Status-Expiry-Index","KeySchema": [{"AttributeName": "BlobStatus", "KeyType": "HASH"},{"AttributeName": "Expiry", "KeyType": "RANGE"}],"Projection": {"ProjectionType": "ALL"},"ProvisionedThroughput": {"ReadCapacityUnits": 5, "WriteCapacityUnits": 5}}]'
      - "--endpoint-url"
      - "http://{{.services.localstack.ip_address}}:4566/"
      - "--region"
      - "us-east-1"

  - name: create-dynamo-store-table
    image: amazon/aws-cli:2.13.2
    env:
      AWS_ACCESS_KEY_ID: "localstack"
      AWS_SECRET_ACCESS_KEY: "localstack"
    cmd:
      - "dynamodb"
      - "create-table"
      - "--table-name"
      - "test-BucketStore"
      - "--attribute-definitions"
      - "AttributeName=RequesterID,AttributeType=S"
      - "--key-schema"
      - "AttributeName=RequesterID,KeyType=HASH"
      - "--provisioned-throughput"
      - "ReadCapacityUnits=10,WriteCapacityUnits=10"
      - "--endpoint-url"
      - "http://{{.services.localstack.ip_address}}:4566/"
      - "--region"
      - "us-east-1"

  - name: churner
    image: eigenda-churner
    build_cmd: "docker build . -t eigenda-churner --target churner"
    ports:
      grpc:
        number: 8080
        transport_protocol: TCP
        application_protocol: "grpc"
      metrics:
        number: 9100
        transport_protocol: TCP
        application_protocol: "http"
    env:
      CHURNER_LOG_LEVEL: debug
      CHURNER_VERBOSE: true
      CHURNER_HOSTNAME: "churner"
      CHURNER_GRPC_PORT: "8080"
      CHURNER_BLS_OPERATOR_STATE_RETRIVER: "{{.addresses.EigenDA.operatorStateRetriever}}"
      CHURNER_EIGENDA_SERVICE_MANAGER: "{{.addresses.EigenDA.serviceManager}}"
      CHURNER_CHAIN_RPC: "{{.http_rpc_url}}"
      # This removes the leading 0x from the key
      CHURNER_PRIVATE_KEY: "{{slice .keys.churner_key.private_key 2}}"
      CHURNER_GRAPH_URL: ""
      CHURNER_INDEXER_PULL_INTERVAL: "1s"
      CHURNER_ENABLE_METRICS: "true"
      CHURNER_METRICS_HTTP_PORT: "9100"
      CHURNER_CHURN_APPROVAL_INTERVAL: "900s"

  - name: disperser
    image: eigenda-apiserver
    build_cmd: "docker build . -t eigenda-apiserver --target apiserver"
    ports:
      grpc:
        number: 8080
        transport_protocol: TCP
        application_protocol: "grpc"
      metrics:
        number: 9100
        transport_protocol: TCP
        application_protocol: "http"
    env:
      DISPERSER_SERVER_LOG_LEVEL: debug
      DISPERSER_SERVER_VERBOSE: true
      DISPERSER_SERVER_S3_BUCKET_NAME: "test-eigenda-blobstore"
      DISPERSER_SERVER_DYNAMODB_TABLE_NAME: "test-BlobMetadata"
      DISPERSER_SERVER_RATE_BUCKET_TABLE_NAME: ""
      DISPERSER_SERVER_RATE_BUCKET_STORE_SIZE: "100000"
      DISPERSER_SERVER_GRPC_PORT: "8080"
      DISPERSER_SERVER_ENABLE_METRICS: "true"
      DISPERSER_SERVER_METRICS_HTTP_PORT: "9100"
      DISPERSER_SERVER_CHAIN_RPC: "{{.http_rpc_url}}"
      # This removes the leading 0x from the key
      DISPERSER_SERVER_PRIVATE_KEY: "{{slice .keys.disperser_key.private_key 2}}"
      DISPERSER_SERVER_NUM_CONFIRMATIONS: "0"
      DISPERSER_SERVER_REGISTERED_QUORUM_ID: "0,1"
      DISPERSER_SERVER_TOTAL_UNAUTH_BYTE_RATE: "10000000,10000000"
      DISPERSER_SERVER_PER_USER_UNAUTH_BYTE_RATE: "32000,32000"
      DISPERSER_SERVER_TOTAL_UNAUTH_BLOB_RATE: "10,10"
      DISPERSER_SERVER_PER_USER_UNAUTH_BLOB_RATE: "2,2"
      DISPERSER_SERVER_ENABLE_RATELIMITER: "true"
      DISPERSER_SERVER_RETRIEVAL_BLOB_RATE: "4"
      DISPERSER_SERVER_RETRIEVAL_BYTE_RATE: "10000000"
      DISPERSER_SERVER_BUCKET_SIZES: "5s"
      DISPERSER_SERVER_BUCKET_MULTIPLIERS: "1"
      DISPERSER_SERVER_COUNT_FAILED: "true"
      DISPERSER_SERVER_BLS_OPERATOR_STATE_RETRIVER: "{{.addresses.EigenDA.operatorStateRetriever}}"
      DISPERSER_SERVER_EIGENDA_SERVICE_MANAGER: "{{.addresses.EigenDA.serviceManager}}"
      DISPERSER_SERVER_AWS_ENDPOINT_URL: "http://{{.services.localstack.ip_address}}:4566"
      DISPERSER_SERVER_AWS_REGION: "us-east-1"
      DISPERSER_SERVER_AWS_ACCESS_KEY_ID: localstack
      DISPERSER_SERVER_AWS_SECRET_ACCESS_KEY: localstack

  - name: encoder
    image: eigenda-encoder
    build_cmd: "docker build . -t eigenda-encoder --target encoder"
    ports:
      grpc:
        number: 8080
        transport_protocol: TCP
        application_protocol: "grpc"
      metrics:
        number: 9100
        transport_protocol: TCP
        application_protocol: "http"
    input:
      /kzg/: kzg_config
    env:
      DISPERSER_ENCODER_LOG_LEVEL: debug
      DISPERSER_ENCODER_VERBOSE: true
      DISPERSER_ENCODER_GRPC_PORT: "8080"
      DISPERSER_ENCODER_ENABLE_METRICS: "true"
      DISPERSER_ENCODER_METRICS_HTTP_PORT: "9100"
      DISPERSER_ENCODER_AWS_REGION: "us-east-1"
      DISPERSER_ENCODER_G1_PATH: /kzg/g1.point
      DISPERSER_ENCODER_G2_PATH: /kzg/g2.point
      DISPERSER_ENCODER_CACHE_PATH: /kzg/cache
      DISPERSER_ENCODER_SRS_ORDER: 3000
      DISPERSER_ENCODER_SRS_LOAD: 2900

  - name: retriever
    image: eigenda-retriever
    build_cmd: "docker build . -t eigenda-retriever --target retriever"
    ports:
      grpc:
        number: 8080
        transport_protocol: TCP
        application_protocol: "grpc"
      metrics:
        number: 9100
        transport_protocol: TCP
        application_protocol: "http"
    input:
      /kzg/: kzg_config
    env:
      RETRIEVER_LOG_LEVEL: debug
      RETRIEVER_VERBOSE: true
      RETRIEVER_HOSTNAME: "retriever"
      RETRIEVER_GRPC_PORT: "8080"
      RETRIEVER_TIMEOUT: "20s"
      RETRIEVER_BLS_OPERATOR_STATE_RETRIVER: "{{.addresses.EigenDA.operatorStateRetriever}}"
      RETRIEVER_EIGENDA_SERVICE_MANAGER: "{{.addresses.EigenDA.serviceManager}}"
      RETRIEVER_G1_PATH: /kzg/g1.point
      RETRIEVER_G2_PATH: /kzg/g2.point
      RETRIEVER_CACHE_PATH: /kzg/cache
      RETRIEVER_SRS_ORDER: 3000
      RETRIEVER_SRS_LOAD: 2900
      RETRIEVER_CHAIN_RPC: "{{.http_rpc_url}}"
      RETRIEVER_PRIVATE_KEY: "{{slice .keys.disperser_key.private_key 2}}"
      RETRIEVER_ENABLE_METRICS: true
      RETRIEVER_METRICS_HTTP_PORT: 9100
      RETRIEVER_GRAPH_URL: ""

  - name: batcher
    image: eigenda-batcher
    build_cmd: "docker build . -t eigenda-batcher --target batcher"
    ports:
      metrics:
        number: 9100
        transport_protocol: TCP
        application_protocol: "http"
        wait: null
    env:
      BATCHER_LOG_LEVEL: debug
      BATCHER_VERBOSE: true
      BATCHER_S3_BUCKET_NAME: "test-eigenda-blobstore"
      BATCHER_DYNAMODB_TABLE_NAME: "test-BlobMetadata"
      BATCHER_PULL_INTERVAL: "1s"
      BATCHER_BLS_OPERATOR_STATE_RETRIVER: "{{.addresses.EigenDA.operatorStateRetriever}}"
      BATCHER_EIGENDA_SERVICE_MANAGER: "{{.addresses.EigenDA.serviceManager}}"
      BATCHER_ENCODER_ADDRESS: "{{.services.encoder.ip_address}}:8080"
      BATCHER_ENABLE_METRICS: true
      BATCHER_METRICS_HTTP_PORT: 9100
      BATCHER_BATCH_SIZE_LIMIT: 10240
      BATCHER_USE_GRAPH: false
      BATCHER_GRAPH_URL: ""
      BATCHER_SRS_ORDER: 3000
      BATCHER_CHAIN_RPC: "{{.http_rpc_url}}"
      # This removes the leading "0x" from the private key
      BATCHER_PRIVATE_KEY: "{{slice .keys.disperser_key.private_key 2}}"
      BATCHER_AWS_REGION: "us-east-1"
      BATCHER_KMS_KEY_DISABLE: true
      BATCHER_KMS_KEY_ID: ""
      BATCHER_KMS_KEY_REGION: ""
      BATCHER_AWS_ACCESS_KEY_ID: "localstack"
      BATCHER_AWS_SECRET_ACCESS_KEY: "localstack"
      BATCHER_AWS_ENDPOINT_URL: "http://{{.services.localstack.ip_address}}:4566"
      BATCHER_FINALIZATION_BLOCK_DELAY: 0

  - name: traffic-generator
    image: traffic-generator
    build_cmd: docker build . -t traffic-generator -f trafficgenerator.Dockerfile
    cmd:
      - "--traffic-generator.disperser-hostname"
      - "{{.services.disperser.ip_address}}"
      - "--traffic-generator.disperser-port"
      - "8080"
      - "--traffic-generator.num-instances"
      - "1"
      - "--traffic-generator.request-interval"
      - "5s"
      - "--traffic-generator.data-size"
      - "1024"

# Specify keys to generate
keys:
  - name: churner_key
    type: ecdsa
  - name: staker1_key
    type: ecdsa
  - name: operator1_ecdsa
    type: ecdsa
  - name: operator1_bls
    type: bls
  - name: disperser_key
    type: ecdsa

artifacts:
  eigenda_deploy_config:
    files:
      eigenda_deploy_config.json:
        template: |
          {
            "numStrategies": 2,
            "confirmerPrivateKey": "{{.keys.disperser_key.private_key}}",
            "stakerPrivateKeys": ["{{.keys.staker1_key.private_key}}"],
            "stakerTokenAmounts": [["0xe8d4a51000"], ["0xe8d4a51000"]],
            "operatorPrivateKeys": ["{{.keys.operator1_ecdsa.private_key}}"],
            "useDefaults": false,
            "eigenLayerCommunityMultisig": "{{.deployer_address}}",
            "eigenLayerOperationsMultisig": "{{.deployer_address}}",
            "eigenLayerPauserMultisig": "{{.deployer_address}}",
            "eigenDACommunityMultisig": "{{.deployer_address}}",
            "eigenDAPauser": "{{.deployer_address}}",
            "churner": "{{.keys.churner_key.address}}",
            "ejector": "{{.deployer_address}}",
            "initialSupply": "0x3635c9adc5dea00000",
            "tokenOwner": "{{.deployer_address}}",
            "maxOperatorCount": 3
          }

  kzg_config:
    files:
      g1.point:
        static_file: "inabox/resources/kzg/g1.point"
      g2.point:
        static_file: "inabox/resources/kzg/g2.point"
      g2.point.powerOf2:
        static_file: "inabox/resources/kzg/g2.point.powerOf2"

# ethereum-package configuration
ethereum_package:
  additional_services:
    - blockscout
  network_params:
    seconds_per_slot: 1
