deployments:
  - name: EigenDA
    repo: https://github.com/Layr-Labs/eigenda.git
    ref: master
    contracts_path: contracts
    script: script/SetUpEigenDA.s.sol:SetupEigenDA
    input:
      script/input/: eigenda_deploy_config
    output:
      eigenda_addresses: script/output/eigenda_deploy_output.json
    addresses:
      serviceManager: "eigenda_addresses:.eigenDAServiceManager"
      operatorStateRetriever: "eigenda_addresses:.operatorStateRetriever"

  - name: MockRollup
    repo: https://github.com/Layr-Labs/eigenda.git
    ref: master
    contracts_path: contracts
    script: script/MockRollupDeployer.s.sol:MockRollupDeployer
    extra_args: "--sig run(address) -- $EIGENDA_SERVICE_MANAGER"
    env:
      EIGENDA_SERVICE_MANAGER: "{{.addresses.EigenDA.serviceManager}}"

services:
  - name: localstack
    image: localstack/localstack
    ports:
      gateway:
        number: 4566
        transport_protocol: TCP
        application_protocol: "http"
    cmd: []

  - name: churner
    image: eigenda-churner
    build_cmd: "docker build . -t eigenda-churner --target churner"
    ports:
      grpc:
        number: 8080
        transport_protocol: TCP
        application_protocol: "grpc"
      metrics:
        number: 9100
        transport_protocol: TCP
        application_protocol: "http"
    env:
      CHURNER_HOSTNAME: "unused"
      CHURNER_GRPC_PORT: "8080"
      CHURNER_BLS_OPERATOR_STATE_RETRIVER: "{{.addresses.EigenDA.operatorStateRetriever}}"
      CHURNER_EIGENDA_SERVICE_MANAGER: "{{.addresses.EigenDA.serviceManager}}"
      CHURNER_CHAIN_RPC: "{{.http_rpc_url}}"
      CHURNER_PRIVATE_KEY: "{{.deployer_private_key}}"
      CHURNER_GRAPH_URL: ""
      CHURNER_INDEXER_PULL_INTERVAL: "1s"
      CHURNER_ENABLE_METRICS: "true"
      CHURNER_METRICS_HTTP_PORT: "9100"
      CHURNER_CHURN_APPROVAL_INTERVAL: "900s"

# Specify keys to generate
keys:
  - name: operator1_ecdsa
    type: ecdsa
  - name: operator1_bls
    type: bls

artifacts:
  eigenda_deploy_config:
    files:
      eigenda_deploy_config.json: |
        {
          "numStrategies": 0,
          "confirmerPrivateKey": "0x{{.deployer_private_key}}",
          "stakerPrivateKeys": [],
          "stakerTokenAmounts": [],
          "operatorPrivateKeys": [],
          "useDefaults": true,
          "eigenLayerCommunityMultisig": "",
          "eigenLayerOperationsMultisig": "",
          "eigenLayerPauserMultisig": "",
          "eigenDACommunityMultisig": "",
          "eigenDAPauser": "",
          "churner": "",
          "ejector": "",
          "initialSupply": 1e12,
          "tokenOwner": "",
          "maxOperatorCount": 3
        }

# ethereum-package configuration
ethereum_package:
  additional_services:
    - blockscout
  network_params:
    seconds_per_slot: 3
