# Example devnet config file for the hello-world-avs example
deployments:
  - name: EigenLayer
    repo: "https://github.com/Layr-Labs/hello-world-avs.git"
    ref: "9b8231b16c8bacd4a5eb67e8faa389cd8b1e9600"
    contracts_path: "contracts"
    script: script/DeployEigenLayerCore.s.sol
    env:
      # NOTE: this is used inside the deployer script
      PRIVATE_KEY: "$deployer_private_key"
      # NOTE: these are needed because of repo's `foundry.toml`
      HOLESKY_PRIVATE_KEY: ""
      HOLESKY_RPC_URL: ""
      ETHERSCAN_API_KEY: ""
    output:
      eigenlayer_addresses: "deployments/core/31337.json"

  - name: hello-world-avs
    repo: "https://github.com/Layr-Labs/hello-world-avs.git"
    ref: "9b8231b16c8bacd4a5eb67e8faa389cd8b1e9600"
    contracts_path: "contracts"
    script: script/HelloWorldDeployer.s.sol
    env:
      # NOTE: this is used inside the deployer script
      PRIVATE_KEY: "$deployer_private_key"
      # NOTE: these are needed because of repo's `foundry.toml`
      HOLESKY_PRIVATE_KEY: ""
      HOLESKY_RPC_URL: ""
      ETHERSCAN_API_KEY: ""
    input:
      deployments/core/: eigenlayer_addresses
    output:
      avs_addresses: "deployments/hello-world/31337.json"

services:
  - name: "operator"
    # NOTE: this image is build locally by the Makefile
    image: "hello_world"
    input:
      /app/contracts/deployments/core/: eigenlayer_addresses
      /app/contracts/deployments/hello-world/: avs_addresses
    env:
      # This expands to the RPC node's URL
      RPC_URL: "$http_rpc_url"
      PRIVATE_KEY: "$keystores.operator_ecdsa_keystore.private_key"
    cmd: ["npm", "run", "start:operator"]

  - name: "traffic-generator"
    # NOTE: this image is build locally by the Makefile
    image: "hello_world"
    input:
      /app/contracts/deployments/core/: eigenlayer_addresses
      /app/contracts/deployments/hello-world/: avs_addresses
    env:
      # This expands to the RPC node's URL
      RPC_URL: "$http_rpc_url"
      PRIVATE_KEY: "$keystores.traffic_generator_ecdsa_keystore.private_key"
    cmd: ["sh", "-c", "sleep 30 ; npm run start:traffic"]

keystores:
  - name: operator_ecdsa_keystore
    type: ecdsa
  - name: traffic_generator_ecdsa_keystore
    type: ecdsa

ethereum_package:
  participants:
    - el_type: erigon
  additional_services:
    - blockscout
    - dora
  network_params:
    # We use the chain ID hardcoded in the hello-world-avs example
    network_id: "31337"
