# Example devnet config file for the incredible-squaring-avs example
deployments:
  - type: EigenLayer
    # This commit corresponds to the incredible-squaring commit below
    ref: "f13e1c21c5c4a90f1550fb80c132428bbacd731c"
    # NOTE: operator registration is done at operator startup

  - name: incredible-squaring
    repo: "https://github.com/Layr-Labs/incredible-squaring-avs.git"
    ref: "d05341ef33e5853fd3ecef831ae4dcfbf29c5299"
    contracts_path: "contracts"
    script: script/IncredibleSquaringDeployer.s.sol
    input:
      script/output/3151908: eigenlayer_addresses
    output:
      avs_addresses: "script/output/3151908/credible_squaring_avs_deployment_output.json"

services:
  - name: "aggregator"
    image: "ghcr.io/layr-labs/incredible-squaring/aggregator/cmd/main.go:latest"
    ports:
      rpc:
        number: 8090
        transport_protocol: "TCP"
        application_protocol: "http"
    # NOTE: aggregator key-pair is hardcoded in the deployment scripts
    address: "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"
    input:
      /usr/src/app/config-files/:
        - aggregator-config
        - avs_addresses
    cmd:
      - "--config"
      - "/usr/src/app/config-files/aggregator-config.yaml"
      - "--ecdsa-private-key"
      - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
      - "--credible-squaring-deployment"
      - "/usr/src/app/config-files/credible_squaring_avs_deployment_output.json"

  - name: "operator1"
    image: "ghcr.io/layr-labs/incredible-squaring/operator/cmd/main.go:latest"
    ports:
      node:
        number: 8080
        transport_protocol: "TCP"
        application_protocol: "http"
        wait: "3m"
    input:
      /usr/src/app/config-files/:
        - operator-config
        - operator1_bls_keystore
        - operator1_ecdsa_keystore
    env:
      OPERATOR_ECDSA_KEY_PASSWORD: $keystores.operator1_ecdsa_keystore.password
      OPERATOR_BLS_KEY_PASSWORD: $keystores.operator1_bls_keystore.password
    cmd: ["--config", "/usr/src/app/config-files/operator-config.yaml"]

keystores:
  - name: "operator1_bls_keystore"
    type: "bls"
  - name: "operator1_ecdsa_keystore"
    type: "ecdsa"

artifacts:
  aggregator-config:
    files:
      aggregator-config.yaml: |
        # 'production' only prints info and above. 'development' also prints debug
        environment: production
        eth_rpc_url: {{.http_rpc_url}}
        eth_ws_url: {{.ws_rpc_url}}
        # address which the aggregator listens on for operator signed messages
        aggregator_server_ip_port_address: 0.0.0.0:8090

  operator-config:
    # TODO: maybe add this eagerly
    additional_data:
      avs_addresses:
        avs_registry_coordinator_address: ".addresses.registryCoordinator"
        operator_state_retriever_address: ".addresses.operatorStateRetriever"
        token_strategy_addr: ".addresses.erc20MockStrategy"
    files:
      operator-config.yaml: |
        production: False
        operator_address: {{.keystores.operator1_ecdsa_keystore.address}}
        avs_registry_coordinator_address: {{.avs_registry_coordinator_address}}
        operator_state_retriever_address: {{.operator_state_retriever_address}}
        eth_rpc_url: {{.http_rpc_url}}
        eth_ws_url: {{.ws_rpc_url}}
        ecdsa_private_key_store_path: /usr/src/app/config-files/1.ecdsa.key.json
        bls_private_key_store_path: /usr/src/app/config-files/1.bls.key.json
        aggregator_server_ip_port_address: {{.services.aggregator.ip_address}}:8090
        eigen_metrics_ip_port_address: "0.0.0.0:8081"
        enable_metrics: False
        node_api_ip_port_address: "0.0.0.0:8080"
        enable_node_api: True
        register_operator_on_startup: True
        token_strategy_addr: {{.token_strategy_addr}}

ethereum_package:
  participants:
    - el_type: erigon
  additional_services:
    - blockscout
    - dora
