name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  KURTOSIS_VERSION: '1.3.1'


jobs:
  # TODO: fix package when running geth+lh
  # run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Setup Kurtosis
  #       run: |
  #         echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
  #         sudo apt update
  #         sudo apt install kurtosis-cli=${{ env.KURTOSIS_VERSION }}
  #         kurtosis analytics disable
  #         echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH
  #       shell: bash

  #     - name: Run Package with default args
  #       run: |
  #         kurtosis run ./kurtosis_package

  run_examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - devnet
          - incredible_squaring
          - hello_world
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli=${{ env.KURTOSIS_VERSION }}
          kurtosis analytics disable
          echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH
        shell: bash

      - name: Run example '${{ matrix.example }}'
        run: make start_${{ matrix.example }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli=${{ env.KURTOSIS_VERSION }}
          kurtosis analytics disable
          echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH
        shell: bash

      - name: Kurtosis Lint
        run: kurtosis lint ./kurtosis_package
